# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_roll_master"

# Version of this mod.
version = "1.2.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Roll Master"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
Link has become a master of rolling!

This mod improves Link's rolling by removing the brief pause between rolls, allowing for fluid, continuous movement. You also have directional control during a roll, allowing a bit more flexibility in your movement.

Optionally, rolling is even faster when wearing the Bunny Hood, making traversal quicker and more responsive. To keep things balanced, speed is clamped when jumping with the Bunny Hood to prevent unintended skips or sequence breaks.

There are also optional dust particles when you roll to give you a sense of speed, this can be turned off in the config options too.
"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "Roll around at the speed of sound"

# Authors of this mod.
authors = [ "Keanine" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
    
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_roll_master"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [ "thumb.dds" ]

[[manifest.config_options]]
id = "bunny_roll"
name = "Bunny Hood Roll"
description = """
Roll even faster with the bunny hood!

Your speed while jumping will be clamped, so you will jump the same distance as the original game, but you can enjoy the benefits of faster movement with this option.
"""
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Enabled"

[[manifest.config_options]]
id = "roll_turning"
name = "Roll Turning"
description = "Allows you to turn slightly while rolling, similar to Twilight Princess. Roll turning could cause issues with speedrun tech, so it's recommended to only disable it for those reasons."
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Enabled"

[[manifest.config_options]]
id = "input_buffer"
name = "Roll Input Buffer"
description = "Add an input buffer to chain together rolls more easily, keeping your max speed high."
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Enabled"

[[manifest.config_options]]
id = "loud_link"
name = "Loud Link"
description = "Link shouts every time he rolls."
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Enabled"

[[manifest.config_options]]
id = "no_interruptions"
name = "No Interruptions"
description = "Link doesn't try to talk to someone or pickup something in the middle of a roll."
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Enabled"

[[manifest.config_options]]
id = "dust_particles"
name = "Dust Particles"
description = "Spawn dust particles when you're rolling around at the speed of sound. This adds a sense of speed and a gives the roll a little more impact."
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Enabled"